### ISSUE TITLE
Wrong version in log & mod menu

### ISSUE THREAD

**Issue by ghost** [marcus8448/GamemodeOverhaul#10]
I am using 2.0.2 but logs and mod menu say 2.0.1 also mod menu is missing a link to the github issues page and author name

![version](https://user-images.githubusercontent.com/82549089/176722248-76e28381-2897-4ca1-841c-339218ad7def.png)

![modmenu](https://user-images.githubusercontent.com/82549089/176722254-723d0d21-d214-416d-a4b3-fe6dfdfcc174.png)

**Comment by marcus8448** [comment]
Should be fixed in version 2.0.3.
Thanks for all your bug reports!
