### ISSUE TITLE
Fabric 1.19 short hand commands not working

### ISSUE THREAD

**Issue by ghost** [marcus8448/GamemodeOverhaul#9]
![image](https://user-images.githubusercontent.com/82549089/176248500-e5c5dfd5-8073-4553-9130-13aad55c4442.png)

**Comment by marcus8448** [comment]
I can't seem to reproduce this. Make sure that the commands are enabled in `.minecraft/config/gamemodeoverhaul.json`

**Comment by ghost** [comment]
> I can't seem to reproduce this. Make sure that the commands are enabled in `.minecraft/config/gamemodeoverhaul.json`

What if I can't find that config file?

**Comment by marcus8448** [comment]
> What if I can't find that config file?

Then something is very wrong. Are you sure its not there? The `config` folder should be located in the same folder as your `mods` folder, if that helps.

GamemodeOverhaul fabric 2.0.3 should have a config screen if you have ModMenu and Cloth Config installed.

**Comment by ghost** [comment]
> > What if I can't find that config file?
> 
> Then something is very wrong. Are you sure its not there? The `config` folder should be located in the same folder as your `mods` folder, if that helps.
> 
> GamemodeOverhaul fabric 2.0.3 should have a config screen if you have ModMenu and Cloth Config installed.

Yeah the config file was just not showing up. But now with 2.0.3 I can go into the config screen and now the config file appears however the /gmc and /gms and /gmsp commands still do not work.

Here is what my config file looks like
{
  "enable_gamemode": true,
  "enable_gm": true,
  "enable_no_args_gm": true,
  "enable_default_gamemode": true,
  "enable_dgm": false,
  "enable_difficulty": true,
  "enable_toggledownfall": true
}

If you want to try for yourself I am using the Vanilla Tweaks 1.19 pack (v7) on the Technic Launcher

**Comment by marcus8448** [comment]
I've tested it with your pack and it works. (FYI: you seem to have the forge version of clumps installed in the pack)
![2022-07-13](https://user-images.githubusercontent.com/28928887/178853193-0943aeb4-d8e2-429d-87d5-12f5b03e7a4c.png)
Note that GamemodeOverhaul is a (logical-)server sided mod; if you're joining a server that doesn't have GamemodeOverhaul installed the commands will not work,

**Comment by marcus8448** [comment]
I have released an update (2.1.0) that should let you use the mod on the client (while connected to a server without the mod).
